import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';
import os from 'os';

// Parse .env for OBSIDIAN_VAULT_PATH
let env = {};
if (fs.existsSync('.env')) {
	const envFile = fs.readFileSync('.env', 'utf8');
	envFile.split('\n').forEach(line => {
		const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
		if (match) {
			let value = match[2] || '';
			value = value.replace(/(^['"]|['"]$)/g, ''); // strip quotes
			env[match[1]] = value;
		}
	});
}
let vaultPath = env.OBSIDIAN_VAULT_PATH;
if (vaultPath && vaultPath.startsWith('~/')) {
    vaultPath = path.join(os.homedir(), vaultPath.slice(2));
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outDir = 'build';

const copyAndReplacePlugin = {
	name: 'copy-and-replace-plugin',
	setup(build) {
		build.onLoad({ filter: /pglite/ }, async (args) => {
			let text = await fs.promises.readFile(args.path, 'utf8');
			text = text.replace(/import\.meta\.url/g, "(window.app.vault.adapter.getResourcePath('.obsidian/plugins/embedding-viewer/main.js').split('?')[0])");
			return { contents: text, loader: 'js' };
		});
		build.onEnd(() => {
			if (!fs.existsSync(outDir)) {
				fs.mkdirSync(outDir, { recursive: true });
			}

			const pgliteDist = 'node_modules/@electric-sql/pglite/dist';
			const vectorDist = 'node_modules/@electric-sql/pglite-pgvector/dist';
			const filesToCopy = [
				path.join(pgliteDist, 'pglite.wasm'),
				path.join(pgliteDist, 'pglite.data'),
				path.join(pgliteDist, 'initdb.wasm'),
				path.join(vectorDist, 'vector.tar.gz'),
				'manifest.json',
				'styles.css'
			];

			filesToCopy.forEach(f => {
				if (fs.existsSync(f)) {
					fs.copyFileSync(f, path.join(outDir, path.basename(f)));
				}
			});

			if (vaultPath) {
				const pluginDir = path.join(vaultPath, '.obsidian', 'plugins', 'embedding-viewer');
				if (!fs.existsSync(pluginDir)) {
					fs.mkdirSync(pluginDir, { recursive: true });
				}
				const buildFiles = fs.readdirSync(outDir);
				buildFiles.forEach(f => {
					fs.copyFileSync(path.join(outDir, f), path.join(pluginDir, f));
				});
				console.log(`Copied build artifacts to ${pluginDir}`);
			} else {
				console.log('OBSIDIAN_VAULT_PATH not set in .env. Skipping copy to Obsidian vault.');
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	mainFields: ['main', 'module'],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: outDir,
	minify: false,
	plugins: [copyAndReplacePlugin],
});

const workerCopyPlugin = {
	name: 'worker-copy-plugin',
	setup(build) {
		build.onEnd(() => {
			if (vaultPath) {
				const pluginDir = path.join(vaultPath, '.obsidian', 'plugins', 'embedding-viewer');
				const workerSrc = path.join(outDir, 'worker.js');
				if (fs.existsSync(workerSrc)) {
					fs.copyFileSync(workerSrc, path.join(pluginDir, 'worker.js'));
				}
			}
		});
	}
};

const workerReplacePlugin = {
	name: 'worker-replace-plugin',
	setup(build) {
		build.onLoad({ filter: /pglite/ }, async (args) => {
			let text = await fs.promises.readFile(args.path, 'utf8');
			text = text.replace(/import\.meta\.url/g, "self.WORKER_BASE_URL");
			return { contents: text, loader: 'js' };
		});
	}
};

const workerContext = await esbuild.context({
	entryPoints: ['src/worker.ts'],
	bundle: true,
	format: 'iife',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: path.join(outDir, 'worker.js'),
	minify: prod,
	define: {
		'process.browser': 'true'
	},
	plugins: [workerCopyPlugin, workerReplacePlugin],
});

if (prod) {
	await context.rebuild();
	await workerContext.rebuild();
	process.exit(0);
} else {
	await context.watch();
	await workerContext.watch();
}
